language: ruby
before_install:
  - gem install bundler
  - rvm list known
rvm:
  - 1.8
  - 1.9
  - 2.0
  - 2.1
  - 2.2
  - 2.3
  - jruby-9.1.5.0
  - rbx-3.9
matrix:
  allow_failures:
  - rvm: rbx-3.9
